#a woman went to the market the items are yam,sugar,groundnut,cassava
print("enter your first item")
firstitem=input()
print("enter the first item price")
firstitem_price=float(input())
print("enter your second item")
seconditem=input()
print("enter the second item price")
seconditem_price=float(input())
print("enter your third item")
thirditem=input()
print("enter third item price")
thirditem_price=float(input())
print("enter your fourth item")
fourthitem=input()
print("enter fourth item price ")
fourthitem_price=float(input())
print("detail: " + firstitem + ":" + str(firstitem_price) + "," + seconditem + " :" + str(seconditem_price) + " ," + thirditem+ ":" + str(thirditem_price) + " ," +str(fourthitem_price))