print("Enter Your School Details")
print("Enter Your School Name")
schoolname= input()
print("Enter Your School address")
schooladdress=input()
print("Enter Your School Email")
schoolemail=input()
print("Enter Your School Number")
schoolnumber=input()
print("My Details are",schoolname ,schooladdress ,schoolemail ,schoolnumber)
