print("give me three number")
print("What is your first number")
firstnumber= float(input())
print("Give me your Second Number")
secondnumber= float(input())
print("Give me your Third Number")
thirdnumber= float(input())
print("This is all 3 of your numbers")
print("pluh",firstnumber ,secondnumber ,thirdnumber)